name: Reusable Playwright Tests & Allure Report

on:
  # This makes the workflow reusable by other workflows
  workflow_call:
    inputs:
      # Define inputs that the calling workflow can provide
      component:
        type: string
        required: true
        default: 'All'
        description: 'Specify which component tests to run (All, FrontEnd, BackEnd)'
   # secrets:
      # Define secrets that the calling workflow must provide
    #  GITHUB_TOKEN:
     #   required: true
      #  description: 'GitHub token for deploying to GitHub Pages and setting commit status'

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test --reporter=line,allure-playwright
        
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-results
          path: allure-results/
        continue-on-error: true

      - name: Download allure
        uses: actions/download-artifact@v4
        if: always()
        with:
          name: allure-results
          path: allure-results/
        continue-on-error: true

      - name: Load Allure history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        id: allure-report
        with:
          allure_results: allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history
          keep_reports: 20

      - name: Deploy to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
          keep_files: true

      - name: Post the link to the report
        if: always()
        uses: Sibz/github-status-action@v1
        with: 
            authToken: ${{secrets.GITHUB_TOKEN}}
            context: 'Test report'
            state: 'success'
            sha: ${{ github.sha }}
            target_url: https://carlosmanzatto.github.io/playwright-01/${{ github.run_number }}
